# Generated by Django 5.1.7 on 2025-03-06 21:59

import plate_detector.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlateDetection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=plate_detector.models.upload_path)),
                ('result_image', models.ImageField(blank=True, null=True, upload_to='results/')),
                ('plate_text', models.CharField(blank=True, max_length=50, null=True)),
                ('confidence', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ocr_method', models.CharField(choices=[('trained', 'Trained Model'), ('tesseract', 'Tesseract OCR')], default='trained', max_length=10)),
            ],
        ),
    ]
